apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: metrics
    port: 9187
    protocol: TCP
    targetPort: 9187
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: .
  namespace: postgres
  labels:
    app: postgres-dr
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: metrics
    port: 9187
    protocol: TCP
    targetPort: 9187
  selector:
    app: postgres-dr