apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret-dr
  namespace: postgres
  labels:
    app: postgres-dr
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword