apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: postgres
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/gal/data/postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: postgres
  name: postgres-volume-dr
  labels:
    type: local
    app: postgres-dr
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/gal/data/postgresql-dr